name: Ansible check centos:centos7  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: ansible check with centos:centos7
      # replace "master" with any valid ref
      uses: roles-ansible/check-ansible-centos-centos7-action@master
      with:
        targets: "./"